In [1]:
import pandas as pd

# Create a Dataframe

In [4]:
pd.DataFrame({'col1': [1,2,3,4,5],
              'col2': [45,65,58,95,45],
             'col3': "asdf lkjh iopu ytre cvbn"})

col1  col2                      col3
0     1    45  asdf lkjh iopu ytre cvbn
1     2    65  asdf lkjh iopu ytre cvbn
2     3    58  asdf lkjh iopu ytre cvbn
3     4    95  asdf lkjh iopu ytre cvbn
4     5    45  asdf lkjh iopu ytre cvbn

In [5]:
"asdf lkjh iopu ytre cvbn".split()

['asdf', 'lkjh', 'iopu', 'ytre', 'cvbn']

In [9]:
df = pd.DataFrame({'col1': [1,2,3,4,5],
              'col2': [45,65,58,95,45],
             'col3': "asdf lkjh iopu ytre cvbn".split()})

In [10]:
df

col1  col2  col3
0     1    45  asdf
1     2    65  lkjh
2     3    58  iopu
3     4    95  ytre
4     5    45  cvbn

In [13]:
# insert 4th column col4 = square of col1
df['col4'] = df['col1']**2

In [14]:
df

col1  col2  col3  col4
0     1    45  asdf     1
1     2    65  lkjh     4
2     3    58  iopu     9
3     4    95  ytre    16
4     5    45  cvbn    25

# APPLY AND LAMBDA FN

In [17]:
# another way using apply function - apply fn is a mapping fn

def test(a):
    return a**2

In [20]:
df['col4_4'] = df['col1'].apply(test)

In [21]:
df

col1  col2  col3  col4 col5  col4_4
0     1    45  asdf     1    a       1
1     2    65  lkjh     4    l       4
2     3    58  iopu     9    i       9
3     4    95  ytre    16    y      16
4     5    45  cvbn    25    c      25

In [15]:
# col5 = first char of col3
df['col5'] = df['col3'].str[0]

In [16]:
df

col1  col2  col3  col4 col5
0     1    45  asdf     1    a
1     2    65  lkjh     4    l
2     3    58  iopu     9    i
3     4    95  ytre    16    y
4     5    45  cvbn    25    c

In [33]:
# if col5 = 'a' then col6 = 'a', if col5 is not 'a' then col6 = z
# custom function like apply function

def test1(v):
    if v == 'a':
        return 'a'
    else:
        return 'z'

In [34]:
df['col6'] = df['col5'].apply(test1)

In [35]:
df

col1  col2  col3  col4 col5  col4_4 col6
0     1    45  asdf     1    a       1    a
1     2    65  lkjh     4    l       4    z
2     3    58  iopu     9    i       9    z
3     4    95  ytre    16    y      16    z
4     5    45  cvbn    25    c      25    z

In [36]:
# if col5 = 'a' then col6 = 'a', if col5 is not 'a' then col6 = z using apply and lambda fn
# custom function like lambda function

df['col6_6'] = df['col5'].apply(lambda x : 'a' if x == 'a' else 'z')

In [37]:
df

col1  col2  col3  col4 col5  col4_4 col6 col6_6
0     1    45  asdf     1    a       1    a      a
1     2    65  lkjh     4    l       4    z      z
2     3    58  iopu     9    i       9    z      z
3     4    95  ytre    16    y      16    z      z
4     5    45  cvbn    25    c      25    z      z

In [40]:
# col7 = length of col3

df['col7'] = df['col3'].apply(len)

In [41]:
df

col1  col2  col3  col4 col5  col4_4 col6 col6_6  col7
0     1    45  asdf     1    a       1    a      a     4
1     2    65  lkjh     4    l       4    z      z     4
2     3    58  iopu     9    i       9    z      z     4
3     4    95  ytre    16    y      16    z      z     4
4     5    45  cvbn    25    c      25    z      z     4

In [ ]:
# col7 = length of col3 using lambda fn

df['col7'] = df['col3'].apply(len)

In [45]:
# col8 = logarithmic value of col2..... math package is not available in the python code

import math

In [46]:
df['col8'] = df['col2'].apply(math.log)

In [47]:
df

col1  col2  col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    45  asdf     1    a       1    a      a     4  3.806662
1     2    65  lkjh     4    l       4    z      z     4  4.174387
2     3    58  iopu     9    i       9    z      z     4  4.060443
3     4    95  ytre    16    y      16    z      z     4  4.553877
4     5    45  cvbn    25    c      25    z      z     4  3.806662

# NUMPY

In [49]:
import numpy as np

In [50]:
l = ['sudh', 1,2,3,4]

In [51]:
type(l)

list

In [52]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [53]:
type(np.array(l))

numpy.ndarray

In [67]:
a1 = np.array([3,4,5,6,3.0])

In [56]:
a = np.array([[1,2], [3,4]])

In [57]:
a

array([[1, 2],
       [3, 4]])

In [58]:
a[1][1]

4

In [68]:
a1[1]

4.0

In [61]:
# 4 dimensional array

a2 = np.array([1,2,3,4], ndmin = 4)

In [62]:
a2

array([[[[1, 2, 3, 4]]]])

In [63]:
a2[0]

array([[[1, 2, 3, 4]]])

In [64]:
a2[0][0]

array([[1, 2, 3, 4]])

In [65]:
a2[0][0][0]

array([1, 2, 3, 4])

In [66]:
a2[0][0][0][0]

1

In [70]:
# 2 dimensional array
a

array([[1, 2],
       [3, 4]])

In [72]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [73]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

# matrix - returns a minimum 2-d array

In [74]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [75]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [76]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [77]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

matrix is also the format of an array
matrix is a sub-class of an array

In [79]:
# matrix is not coverting to an array bcoz matrix is also a sub-class of an array
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [80]:
# create a fn in fromfunction in numpy

np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [81]:
np.fromfunction(lambda i, j : i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [82]:
# for integer value
np.fromfunction(lambda i, j : i*j, (4,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [84]:
# in matrix form
np.mat(np.fromfunction(lambda i, j : i*j, (4,4), dtype = int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

# not able to create 3-D matrix
# np.mat(np.fromfunction(lambda i, j, z : i*j*z, (3,3,2), dtype = int))
show error

In [88]:
# 3-D array - (3,3,2) - 3- 3 matrix - (3,2)- 3 rows and 2 columns

np.fromfunction(lambda i, j, z : i*j*z, (3,3,2), dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [89]:
# 3-D array - (3,3,2) - 4- 4 matrix - (3,2)- 3 rows and 2 columns

np.fromfunction(lambda i, j, z : i*j*z, (4,3,2), dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [91]:
# 3-D array - (3,3,2) - 4- 4 set of 3 matrix - (3,2)- 3 rows and 2 columns

np.fromfunction(lambda i, j, z, x : i*j*z*x, (4,3,2,2), dtype = int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [109]:
# 3-D array - (3,3,2) - 4- 4 matrix - (3,2)- 3 rows and 2 columns

x = np.fromfunction(lambda i, j, z : i*j*z, (4,3,2), dtype = int)

In [110]:
x

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [111]:
# dimension by ndim
x.ndim

3

In [112]:
# no of elements
x.size

24

In [113]:
# dimension 
x.shape

(4, 3, 2)

In [114]:
x.dtype

dtype('int32')

In [115]:
pd.DataFrame(x)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [103]:
x1 = np.fromfunction(lambda i, j: i*j, (400,100), dtype = int)

In [104]:
x1

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [105]:
pd.DataFrame(x1)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [116]:
# random fn

np.random.rand(100,4)

array([[4.48337264e-01, 4.68927774e-01, 3.91218594e-01, 3.81916414e-02],
       [9.51999044e-01, 6.95712596e-01, 8.72816687e-01, 2.48281928e-02],
       [7.68502717e-02, 3.74669859e-01, 7.55868848e-01, 8.78880829e-01],
       [2.05336372e-01, 4.47048916e-01, 4.85777442e-02, 9.14490580e-01],
       [1.11441972e-01, 2.81737344e-01, 7.69624462e-02, 9.76061994e-01],
       [9.44027338e-01, 1.36815419e-01, 6.41495211e-01, 1.76132104e-01],
       [9.91443702e-01, 5.34869901e-01, 7.35092246e-01, 4.25368417e-01],
       [5.41386476e-01, 8.02635981e-01, 9.26224956e-01, 7.58242473e-01],
       [1.02947752e-01, 6.53781994e-01, 2.13442377e-01, 2.20370418e-01],
       [8.95353697e-01, 4.74291076e-01, 6.07753665e-01, 2.40437433e-01],
       [5.01951024e-01, 6.98539347e-01, 1.24709359e-01, 3.24872636e-01],
       [3.47136778e-01, 7.65612377e-01, 3.41545943e-01, 3.89181027e-01],
       [3.67250318e-01, 2.43910294e-01, 1.53414634e-01, 9.30759303e-02],
       [3.71681728e-01, 3.93105644e-01, 4.73908574e

In [117]:
# random integer -> one single random int

np.random.randint(4,50)

21

In [118]:
# randn(4,5) -> 4 rows-5 columns
np.random.randn(4,5)

array([[ 0.84588583, -0.19569165, -0.09579406,  0.62217874, -0.46570226],
       [ 0.85300004,  0.04362607,  0.41379403,  0.26621242,  0.29192843],
       [ 0.2239462 , -0.7683763 ,  1.14408115,  0.17985867,  1.07877857],
       [ 0.96265024, -1.49965348, -0.0169123 ,  0.37290624,  0.84643351]])

# convert 2-D to 3-D

In [123]:
# convert 2-D to 3-D
# 3-D array - (3,3,2) - 4- 4 matrix - (3,2)- 3 rows and 2 columns

p = np.fromfunction(lambda i, j, z : i*j*z, (4,3,2), dtype = int)

In [126]:
p.size

24

In [124]:
p.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [127]:
pd.DataFrame(p.reshape(6,4))

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

# 3-D to 4-D using reshape fn

In [130]:
p.reshape(4,2,1,3)

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [131]:
# -1 means -> taking bydefaut 6
p.reshape(4,-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [132]:
# -1 means -> taking bydefaut 12 columns
p.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [133]:
# any -ve no. means -> taking bydefaut 12 columns
p.reshape(2,-14564654654)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [134]:
# any -ve no. means -> taking bydefaut 3 columns
p.reshape(2,4,-256)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

# range fn

In [136]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [135]:
list(range(4,10,2))

[4, 6, 8]

In [138]:
list(range(4,10,.2)) # step size as a float gives an error

TypeError: 'float' object cannot be interpreted as an integer

In [141]:
list(range(4,10.5,2)) # end pt as a float gives an error

TypeError: 'float' object cannot be interpreted as an integer

In [139]:
# generate a dataset by using arange fn- in this step size is in float - .2
np.arange(4,10,.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [142]:
# generate a dataset by using arange fn- in this step size is in float - .2
a1 = np.arange(4,10.5,.2)

In [144]:
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [143]:
# slicing operation

a1[1:4]

array([4.2, 4.4, 4.6])

In [145]:
arr = np.random.rand(4,5)

In [146]:
arr

array([[0.4283484 , 0.88123049, 0.20077844, 0.72354104, 0.60492013],
       [0.57047703, 0.2057665 , 0.72662519, 0.40300808, 0.11681349],
       [0.93760762, 0.37973709, 0.74551983, 0.63211738, 0.62337511],
       [0.48620891, 0.20937131, 0.57820832, 0.1353503 , 0.89187014]])

In [147]:
arr > .5

array([[False,  True, False,  True,  True],
       [ True, False,  True, False, False],
       [ True, False,  True,  True,  True],
       [False, False,  True, False,  True]])

In [148]:
arr[arr > .5]

array([0.88123049, 0.72354104, 0.60492013, 0.57047703, 0.72662519,
       0.93760762, 0.74551983, 0.63211738, 0.62337511, 0.57820832,
       0.89187014])

In [151]:
# extract nos.
# row no -> 1 & 2
# column no -> 2

arr[[1,2],[2]]

array([0.72662519, 0.74551983])

In [152]:
arr1 = np.random.rand(8,5)

In [153]:
arr1

array([[0.66963849, 0.93652152, 0.82149131, 0.41578548, 0.20669406],
       [0.15298511, 0.6210731 , 0.65002515, 0.06076462, 0.42365117],
       [0.98702385, 0.28657849, 0.40034892, 0.30179964, 0.67302132],
       [0.48746038, 0.04628979, 0.18067384, 0.40856852, 0.10992489],
       [0.72380537, 0.43615307, 0.74571407, 0.52326664, 0.66004861],
       [0.74762834, 0.0264425 , 0.81867561, 0.32910421, 0.99930139],
       [0.55831506, 0.8673637 , 0.79827887, 0.44258751, 0.50424311],
       [0.33695299, 0.35997119, 0.57113841, 0.60253587, 0.31443568]])

In [155]:
arr1[1:8, 0:3]

array([[0.15298511, 0.6210731 , 0.65002515],
       [0.98702385, 0.28657849, 0.40034892],
       [0.48746038, 0.04628979, 0.18067384],
       [0.72380537, 0.43615307, 0.74571407],
       [0.74762834, 0.0264425 , 0.81867561],
       [0.55831506, 0.8673637 , 0.79827887],
       [0.33695299, 0.35997119, 0.57113841]])

In [158]:
a2 = arr1[1:8, [0,1,2]]

In [159]:
a2

array([[0.15298511, 0.6210731 , 0.65002515],
       [0.98702385, 0.28657849, 0.40034892],
       [0.48746038, 0.04628979, 0.18067384],
       [0.72380537, 0.43615307, 0.74571407],
       [0.74762834, 0.0264425 , 0.81867561],
       [0.55831506, 0.8673637 , 0.79827887],
       [0.33695299, 0.35997119, 0.57113841]])

In [160]:
a2[0][0] 

0.15298510972488966

In [161]:
a2[0][0] = 100

In [162]:
a2

array([[1.00000000e+02, 6.21073102e-01, 6.50025148e-01],
       [9.87023852e-01, 2.86578490e-01, 4.00348918e-01],
       [4.87460382e-01, 4.62897889e-02, 1.80673841e-01],
       [7.23805366e-01, 4.36153065e-01, 7.45714073e-01],
       [7.47628343e-01, 2.64425047e-02, 8.18675613e-01],
       [5.58315062e-01, 8.67363699e-01, 7.98278875e-01],
       [3.36952991e-01, 3.59971189e-01, 5.71138411e-01]])

In [163]:
a = np.array([[1,2], [3,4]])
b = np.array([[2,3], [4,5]])

In [164]:
a

array([[1, 2],
       [3, 4]])

In [165]:
b

array([[2, 3],
       [4, 5]])

# matrix multiplication

In [166]:
# element wise multiplication not matrix multiplication 
a*b

array([[ 2,  6],
       [12, 20]])

In [168]:
# matrix multiplication by using @ sign
# column of 1st = row of 2nd nd row of 1st = column of 2nd ---> in numbers like (3,2) - (2,3)
# here both r of (2,2)
a@b

array([[10, 13],
       [22, 29]])

In [169]:
m = a@b

In [170]:
m

array([[10, 13],
       [22, 29]])

In [171]:
# infinity values
m/0

<ipython-input-171-be1849f03ef3>:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])